### PR TITLE
travis: add build check

### PR DESCRIPTION
**Pull request by holger-dengler**
Add automated build check for main repository. Pull requests should at least pass this test-suite.

### CODE REVIEW

**Comment by ifranzki** [comment]
close/reopen to trigger Travis

**Comment by holger-dengler** [comment]
thx!

**Comment by holger-dengler** [comment]
I decided to extend the setup-ock script. If that works, I'll remove most of the setup stuff from the travis file.

**Comment by holger-dengler** [comment]
Jammy seems too outdated for testing this project. I'll close the the PR for now.

**Pull request closed without merging**
